name: GachaRPG
version: ${project.version}
main: dev.failures.main.GachaRPG
api-version: 1.16
commands:
  stats:
    aliases: [info, class, level, stat]
    description: Opens player's character information
  gold:
    aliases: [g]
    description: Displays current balance for player