name: GachaRPG
version: ${project.version}
main: dev.failures.main.GachaRPG
softdepend: ['Multiverse-Core']
api-version: 1.16
commands:
  stats:
    aliases: [info, class, level, stat]
    description: Opens player's character information
  gold:
    aliases: [g]
    description: Displays current balance for player
  party:
    aliases: [p]
    description: Party system for dank serber.
  admin:
    aliases: [gacha]
    description: admin command :)
  lore:
    aliases: [relore]
    description: Relores items
  rename:
    description: Renames items
  skull:
    aliases: [head]
    description: Gives player head